#Admins
Admin.where(email: "admin@mezzweststatetour.com").first_or_create!(password: "mezzwest", super_admin: true)

#Levels
pro = Level.where(name: "Pro").first_or_create!(games_required: 9)
semi_pro = Level.where(name: "Semi-Pro").first_or_create!(games_required: 8)
open = Level.where(name: "Open").first_or_create!(games_required: 7)

#Players
Player.where(first_name: "Aldrin", last_name: "Germiniano").first_or_create!(display_name: "Aldrin", level: open)
Player.where(first_name: "Alex", last_name: "Aguiar").first_or_create!(display_name: "Alex", level: open)
Player.where(first_name: "Alfred", last_name: "Martinez").first_or_create!(display_name: "Alfred", level: open)
Player.where(first_name: "Amar", last_name: "Kang").first_or_create!(display_name: "Amar", level: pro)
Player.where(first_name: "Andrew", last_name: "Park").first_or_create!(display_name: "Andrew", level: open)
Player.where(first_name: "Anthony", last_name: "Ortega").first_or_create!(display_name: "Anthony", level: open)
Player.where(first_name: "Art", last_name: "Garcia").first_or_create!(display_name: "Art", level: open)
Player.where(first_name: "Arturo", last_name: "Rivera").first_or_create!(display_name: "Arturo", level: semi_pro)
Player.where(first_name: "Attila", last_name: "Bezdan").first_or_create!(display_name: "Attila B", level: pro)
Player.where(first_name: "Attila", last_name: "Csorba").first_or_create!(display_name: "Attila C", level: open)
Player.where(first_name: "Babken", last_name: "Melkonyan").first_or_create!(display_name: "Babken", level: semi_pro)
Player.where(first_name: "Barbara", last_name: "Lee").first_or_create!(display_name: "Barbara", level: open)
Player.where(first_name: "Bart", last_name: "Mahoney").first_or_create!(display_name: "Bart", level: semi_pro)
Player.where(first_name: "Beau", last_name: "Runningen").first_or_create!(display_name: "Beau", level: pro)
Player.where(first_name: "Bee", last_name: "Davidson").first_or_create!(display_name: "Bee", level: open)
Player.where(first_name: "Ben", last_name: "Black").first_or_create!(display_name: "Bee", level: open)
Player.where(first_name: "Bill", last_name: "Norrish").first_or_create!(display_name: "Bill N", level: open)
Player.where(first_name: "Bill", last_name: "Villareal").first_or_create!(display_name: "Bill V", level: open)
Player.where(first_name: "Billy", last_name: "Pence").first_or_create!(display_name: "Billy P", level: open)
Player.where(first_name: "Billy", last_name: "Silviera").first_or_create!(display_name: "Billy S", level: open)
Player.where(first_name: "Bob", last_name: "DePlachett").first_or_create!(display_name: "Bob", level: open)
Player.where(first_name: "Bob", last_name: "DePlachett").first_or_create!(display_name: "Bob D", level: open)
Player.where(first_name: "Bob", last_name: "Jocz").first_or_create!(display_name: "Bob J", level: open)
Player.where(first_name: "Bobby", last_name: "Lees").first_or_create!(display_name: "Bobby", level: open)
Player.where(first_name: "Branch", last_name: "Talley").first_or_create!(display_name: "Branch", level: open)
Player.where(first_name: "Brian", last_name: "Elwell").first_or_create!(display_name: "Brian E", level: open)
Player.where(first_name: "Brian", last_name: "Law").first_or_create!(display_name: "Brian L", level: open)
Player.where(first_name: "Brian", last_name: "Parks").first_or_create!(display_name: "Brian P", level: semi_pro)
Player.where(first_name: "Brook", last_name: "Thomason").first_or_create!(display_name: "Brook", level: open)
Player.where(first_name: "Butch", last_name: "Barbra").first_or_create!(display_name: "Butch", level: open)
Player.where(first_name: "Carl", last_name: "Wilson").first_or_create!(display_name: "Carl", level: semi_pro)
Player.where(first_name: "Carlos", last_name: "Mendoza").first_or_create!(display_name: "Carlos", level: open)
Player.where(first_name: "Chad", last_name: "Barber").first_or_create!(display_name: "Chad", level: open)
Player.where(first_name: "Charles", last_name: "Mendiola").first_or_create!(display_name: "Charles", level: open)
Player.where(first_name: "Chris", last_name: "Atkins").first_or_create!(display_name: "Chris A", level: open)
Player.where(first_name: "Chris", last_name: "Fangre").first_or_create!(display_name: "Chris F", level: semi_pro)
Player.where(first_name: "Chris", last_name: "Robinson").first_or_create!(display_name: "Chris R", level: open)
Player.where(first_name: "Chris", last_name: "Wedekin").first_or_create!(display_name: "Chris W", level: open)
Player.where(first_name: "Christy", last_name: "Lipps").first_or_create!(display_name: "Christy", level: open)
Player.where(first_name: "CJ", last_name: "Robinson").first_or_create!(display_name: "CJ", level: open)
Player.where(first_name: "Clint", last_name: "Palaci").first_or_create!(display_name: "Clint", level: open)
Player.where(first_name: "Dale", last_name: "Kadouhl").first_or_create!(display_name: "Dale", level: open)
Player.where(first_name: "Damian", last_name: "Rebman").first_or_create!(display_name: "Damian", level: open)
Player.where(first_name: "Dan", last_name: "Russo").first_or_create!(display_name: "Dan R", level: open)
Player.where(first_name: "Dan", last_name: "Wallace").first_or_create!(display_name: "Dan W", level: semi_pro)
Player.where(first_name: "Dane", last_name: "Elmsteadt").first_or_create!(display_name: "Dane", level: open)
Player.where(first_name: "Daniel", last_name: "Aguiar").first_or_create!(display_name: "Daniel", level: open)
Player.where(first_name: "Danny", last_name: "Gokhul").first_or_create!(display_name: "Danny", level: pro)
Player.where(first_name: "Darryl", last_name: "Taylor").first_or_create!(display_name: "Darryl", level: open)
Player.where(first_name: "Dave", last_name: "Espinoza").first_or_create!(display_name: "Dave E", level: open)
Player.where(first_name: "Dave", last_name: "Gorham").first_or_create!(display_name: "Dave G", level: open)
Player.where(first_name: "Dave", last_name: "Hemmah").first_or_create!(display_name: "Dave H", level: semi_pro)
Player.where(first_name: "Dave", last_name: "Vincent").first_or_create!(display_name: "Dave V", level: open)
Player.where(first_name: "David", last_name: "Delcastillo").first_or_create!(display_name: "David D", level: open)
Player.where(first_name: "David", last_name: "Gomez").first_or_create!(display_name: "David G", level: open)
Player.where(first_name: "David", last_name: "Martineau").first_or_create!(display_name: "David M", level: open)
Player.where(first_name: "Delbert", last_name: "Wong").first_or_create!(display_name: "Delbert", level: open)
Player.where(first_name: "Deo", last_name: "Alpojara").first_or_create!(display_name: "Deo", level: semi_pro)
Player.where(first_name: "Derek", last_name: "Kiim").first_or_create!(display_name: "Derek", level: open)
Player.where(first_name: "Don", last_name: "Davies").first_or_create!(display_name: "Don", level: open)
Player.where(first_name: "Ed", last_name: "Gonzeles").first_or_create!(display_name: "Ed G", level: open)
Player.where(first_name: "Ed", last_name: "Marshton").first_or_create!(display_name: "Ed M", level: open)
Player.where(first_name: "Ed", last_name: "Ramos").first_or_create!(display_name: "Ed R", level: open)
Player.where(first_name: "Ed", last_name: "Sellers").first_or_create!(display_name: "Ed S", level: open)
Player.where(first_name: "Eddie", last_name: "Cohen").first_or_create!(display_name: "Eddie", level: open)
Player.where(first_name: "Edwin", last_name: "Urbano").first_or_create!(display_name: "Edwin", level: open)
Player.where(first_name: "Efren", last_name: "Reyes").first_or_create!(display_name: "Efren", level: pro)
Player.where(first_name: "Emerson", last_name: "Joiner").first_or_create!(display_name: "Emerson", level: open)
Player.where(first_name: "Eric", last_name: "Harada").first_or_create!(display_name: "Eric H", level: open)
Player.where(first_name: "Eric", last_name: "Scott").first_or_create!(display_name: "Eric S", level: open)
Player.where(first_name: "Eric", last_name: "Stanley").first_or_create!(display_name: "Eric S", level: open)
Player.where(first_name: "Ernesto", last_name: "Dominguez").first_or_create!(display_name: "Ernesto", level: pro)
Player.where(first_name: "Fach", last_name: "Garcia").first_or_create!(display_name: "Fach", level: semi_pro)
Player.where(first_name: "Francis", last_name: "Ritarita").first_or_create!(display_name: "Francis", level: open)
Player.where(first_name: "Frank", last_name: "Almanza").first_or_create!(display_name: "Frank A", level: open)
Player.where(first_name: "Frank", last_name: "Giordano").first_or_create!(display_name: "Frank G", level: open)
Player.where(first_name: "Frank", last_name: "Robutz").first_or_create!(display_name: "Frank R", level: open)
Player.where(first_name: "Fransico", last_name: "Bustamante").first_or_create!(display_name: "Fransico", level: pro)
Player.where(first_name: "George", last_name: "Pagulayan").first_or_create!(display_name: "George", level: open)
Player.where(first_name: "Glenn", last_name: "Umemoto").first_or_create!(display_name: "Glenn", level: open)
Player.where(first_name: "Greg", last_name: "Harada").first_or_create!(display_name: "Greg H", level: semi_pro)
Player.where(first_name: "Greg", last_name: "Veach").first_or_create!(display_name: "Greg V", level: open)
Player.where(first_name: "Hiroko", last_name: "Makiyama").first_or_create!(display_name: "Hiroko", level: open)
Player.where(first_name: "Horia", last_name: "Udrea").first_or_create!(display_name: "Horia", level: open)
Player.where(first_name: "Howard", last_name: "Kennedy").first_or_create!(display_name: "Howard", level: open)
Player.where(first_name: "Jack", last_name: "Ritonya").first_or_create!(display_name: "Jack", level: open)
Player.where(first_name: "Jaden", last_name: "Brock").first_or_create!(display_name: "Jaden", level: open)
Player.where(first_name: "James", last_name: "Harris").first_or_create!(display_name: "James", level: open)
Player.where(first_name: "Jason", last_name: "Batin").first_or_create!(display_name: "Jason B", level: open)
Player.where(first_name: "Jason", last_name: "Carandang").first_or_create!(display_name: "Jason C", level: open)
Player.where(first_name: "Jason", last_name: "Ferroni").first_or_create!(display_name: "Jason F", level: open)
Player.where(first_name: "Jason", last_name: "Gilbert").first_or_create!(display_name: "Jason G", level: open)
Player.where(first_name: "Jason", last_name: "Hardcastle").first_or_create!(display_name: "Jason H", level: open)
Player.where(first_name: "Jason", last_name: "Katon").first_or_create!(display_name: "Jason K", level: open)
Player.where(first_name: "Jason", last_name: "Williams").first_or_create!(display_name: "Jason W", level: semi_pro)
Player.where(first_name: "Javier", last_name: "Ramirez").first_or_create!(display_name: "Javier", level: open)
Player.where(first_name: "Jay", last_name: "Helfert").first_or_create!(display_name: "Jay H", level: open)
Player.where(first_name: "Jay", last_name: "Mulibayan").first_or_create!(display_name: "Jay M", level: open)
Player.where(first_name: "Jay", last_name: "Pee").first_or_create!(display_name: "Jay P", level: open)
Player.where(first_name: "Jaynard", last_name: "Orque").first_or_create!(display_name: "Jaynard", level: semi_pro)
Player.where(first_name: "Jeff", last_name: "Gregory").first_or_create!(display_name: "Jeff", level: semi_pro)
Player.where(first_name: "Jenny", last_name: "Lee").first_or_create!(display_name: "Jenny", level: open)
Player.where(first_name: "Jerry", last_name: "Jamito").first_or_create!(display_name: "Jerry J", level: pro)
Player.where(first_name: "Jerry", last_name: "Lin").first_or_create!(display_name: "Jerry L", level: semi_pro)
Player.where(first_name: "Jerry", last_name: "Stuckart").first_or_create!(display_name: "Jerry S", level: open)
Player.where(first_name: "Jim", last_name: "Burt").first_or_create!(display_name: "Jim B", level: open)
Player.where(first_name: "Jim", last_name: "Hennessy").first_or_create!(display_name: "Jim H", level: open)
Player.where(first_name: "Jimmy", last_name: "Qu").first_or_create!(display_name: "Jimmy", level: open)
Player.where(first_name: "Joe", last_name: "Delio").first_or_create!(display_name: "Joe D", level: open)
Player.where(first_name: "Joe", last_name: "Stein").first_or_create!(display_name: "Joe S", level: open)
Player.where(first_name: "Joe", last_name: "Chin").first_or_create!(display_name: "Joe C", level: open)
Player.where(first_name: "John", last_name: "Barioni").first_or_create!(display_name: "John B", level: open)
Player.where(first_name: "John", last_name: "Fergeson").first_or_create!(display_name: "John F", level: open)
Player.where(first_name: "John", last_name: "Nekali").first_or_create!(display_name: "John N", level: open)
Player.where(first_name: "John", last_name: "Ritonya").first_or_create!(display_name: "John R", level: open)
Player.where(first_name: "John", last_name: "Schmidt").first_or_create!(display_name: "John S", level: pro)
Player.where(first_name: "JohnMark", last_name: "Hernandez").first_or_create!(display_name: "JohnMark", level: open)
Player.where(first_name: "Johnny", last_name: "Kang").first_or_create!(display_name: "Johnny", level: pro)
Player.where(first_name: "Josh", last_name: "Gomes").first_or_create!(display_name: "Josh", level: open)
Player.where(first_name: "Juan", last_name: "Ortega").first_or_create!(display_name: "Juan", level: open)
Player.where(first_name: "Junne", last_name: "Padua").first_or_create!(display_name: "Junne", level: open)
Player.where(first_name: "Justin", last_name: "Logan").first_or_create!(display_name: "Justin L", level: open)
Player.where(first_name: "Justin", last_name: "Marks").first_or_create!(display_name: "Justin M", level: open)
Player.where(first_name: "Keith", last_name: "O'Donnel").first_or_create!(display_name: "Keith O", level: open)
Player.where(first_name: "Keith", last_name: "Valet").first_or_create!(display_name: "Keith V", level: open)
Player.where(first_name: "Ken", last_name: "Chang").first_or_create!(display_name: "Ken C", level: open)
Player.where(first_name: "Ken", last_name: "Gouso").first_or_create!(display_name: "Ken G", level: open)
Player.where(first_name: "Ken", last_name: "Johnson").first_or_create!(display_name: "Ken J", level: open)
Player.where(first_name: "Ken", last_name: "Mendoza").first_or_create!(display_name: "Ken M", level: open)
Player.where(first_name: "Ken", last_name: "Thomason").first_or_create!(display_name: "Ken T", level: open)
Player.where(first_name: "Kenny", last_name: "Ash").first_or_create!(display_name: "Kenny A", level: open)
Player.where(first_name: "Kenny", last_name: "Koo").first_or_create!(display_name: "Kenny K", level: open)
Player.where(first_name: "Kevin", last_name: "Collins").first_or_create!(display_name: "Kevin C", level: open)
Player.where(first_name: "Kevin", last_name: "Knucky").first_or_create!(display_name: "Kevin K", level: open)
Player.where(first_name: "Kevin", last_name: "May").first_or_create!(display_name: "Kevin M", level: open)
Player.where(first_name: "KID", last_name: "").first_or_create!(display_name: "KID", level: open)
Player.where(first_name: "Kirk", last_name: "Jewel").first_or_create!(display_name: "Kirk", level: open)
Player.where(first_name: "Kristina", last_name: "Cordova").first_or_create!(display_name: "Kristina", level: open)
Player.where(first_name: "Lance", last_name: "Johnson").first_or_create!(display_name: "Lance", level: open)
Player.where(first_name: "Larry", last_name: "Bohn").first_or_create!(display_name: "Larry", level: open)
Player.where(first_name: "Lee", last_name: "Silkwood").first_or_create!(display_name: "Lee", level: open)
Player.where(first_name: "Lenny", last_name: "Brock").first_or_create!(display_name: "Lenny", level: open)
Player.where(first_name: "Loren", last_name: "Mah").first_or_create!(display_name: "Loren", level: open)
Player.where(first_name: "Lori", last_name: "Jones").first_or_create!(display_name: "Lori", level: open)
Player.where(first_name: "Lorry", last_name: "Deleon").first_or_create!(display_name: "Lorry", level: semi_pro)
Player.where(first_name: "Luke", last_name: "Mahan").first_or_create!(display_name: "Luke", level: open)
Player.where(first_name: "Manual", last_name: "Herrera").first_or_create!(display_name: "Manual", level: open)
Player.where(first_name: "Marcelino", last_name: "Montoya").first_or_create!(display_name: "Marcelino", level: open)
Player.where(first_name: "Mark", last_name: "Tiu").first_or_create!(display_name: "Mark T", level: open)
Player.where(first_name: "Mark", last_name: "Whitehead").first_or_create!(display_name: "Mark W", level: open)
Player.where(first_name: "Marty", last_name: "Carey").first_or_create!(display_name: "Marty", level: open)
Player.where(first_name: "MaryAnn", last_name: "Starkey").first_or_create!(display_name: "MaryAnn", level: open)
Player.where(first_name: "Melinda", last_name: "Huang").first_or_create!(display_name: "Melinda", level: open)
Player.where(first_name: "Melissa", last_name: "Herndon").first_or_create!(display_name: "Melissa", level: open)
Player.where(first_name: "Michael", last_name: "Campos").first_or_create!(display_name: "Michael C", level: open)
Player.where(first_name: "Michael", last_name: "Glass").first_or_create!(display_name: "Michael G", level: open)
Player.where(first_name: "Mike", last_name: "Langarica").first_or_create!(display_name: "Mike L", level: open)
Player.where(first_name: "Mike", last_name: "Laos").first_or_create!(display_name: "Mike L", level: open)
Player.where(first_name: "Mike", last_name: "Meeker").first_or_create!(display_name: "Mike M", level: open)
Player.where(first_name: "Minnie", last_name: "Tayaotao").first_or_create!(display_name: "Minnie", level: open)
Player.where(first_name: "Morro", last_name: "Paez").first_or_create!(display_name: "Morro", level: semi_pro)
Player.where(first_name: "Nate", last_name: "Stipek").first_or_create!(display_name: "Nate", level: open)
Player.where(first_name: "Nick", last_name: "Callado").first_or_create!(display_name: "Nick C", level: open)
Player.where(first_name: "Nick", last_name: "Spano").first_or_create!(display_name: "Nick S", level: semi_pro)
Player.where(first_name: "Nico", last_name: "Scalise").first_or_create!(display_name: "Nico", level: open)
Player.where(first_name: "Omar", last_name: "Vachhani").first_or_create!(display_name: "Omar", level: open)
Player.where(first_name: "Oscar", last_name: "Dominguez").first_or_create!(display_name: "Oscar", level: pro)
Player.where(first_name: "Paul", last_name: "Ewing").first_or_create!(display_name: "Paul E", level: open)
Player.where(first_name: "Paul", last_name: "Higaki").first_or_create!(display_name: "Paul H", level: open)
Player.where(first_name: "Paul", last_name: "Santos").first_or_create!(display_name: "Paul S", level: open)
Player.where(first_name: "Paul", last_name: "Silva").first_or_create!(display_name: "Paul S", level: open)
Player.where(first_name: "Peter", last_name: "Leung").first_or_create!(display_name: "Peter", level: open)
Player.where(first_name: "Phil", last_name: "Prentice").first_or_create!(display_name: "Phil", level: open)
Player.where(first_name: "Ramin", last_name: "Bakhtiari").first_or_create!(display_name: "Ramin", level: semi_pro)
Player.where(first_name: "Ramon", last_name: "Mistica").first_or_create!(display_name: "Ramon", level: pro)
Player.where(first_name: "Randy", last_name: "Hatten").first_or_create!(display_name: "Randy", level: open)
Player.where(first_name: "Ray", last_name: "Moran").first_or_create!(display_name: "Ray M", level: open)
Player.where(first_name: "Ray", last_name: "Pajarillo").first_or_create!(display_name: "Ray P", level: open)
Player.where(first_name: "Ray", last_name: "Rey").first_or_create!(display_name: "Ray R", level: open)
Player.where(first_name: "Ray", last_name: "Robles").first_or_create!(display_name: "Ray R", level: open)
Player.where(first_name: "Reid", last_name: "Flemining").first_or_create!(display_name: "Reid F", level: open)
Player.where(first_name: "Reid", last_name: "Strensrud").first_or_create!(display_name: "Reid S", level: open)
Player.where(first_name: "Rex", last_name: "Chan").first_or_create!(display_name: "Rex", level: open)
Player.where(first_name: "Rich", last_name: "Hodge").first_or_create!(display_name: "Rich", level: open)
Player.where(first_name: "Richard", last_name: "Daniel").first_or_create!(display_name: "Richard", level: open)
Player.where(first_name: "Rob", last_name: "Eggers").first_or_create!(display_name: "Rob", level: open)
Player.where(first_name: "Robbie", last_name: "Ling").first_or_create!(display_name: "Robbie", level: open)
Player.where(first_name: "Robert", last_name: "Laurie").first_or_create!(display_name: "Robert", level: open)
Player.where(first_name: "Rodney", last_name: "Morris").first_or_create!(display_name: "Rodney M", level: pro)
Player.where(first_name: "Rodney", last_name: "Wynn").first_or_create!(display_name: "Rodney W", level: open)
Player.where(first_name: "Rodrigo", last_name: "Geronimo").first_or_create!(display_name: "Rodrigo", level: pro)
Player.where(first_name: "Ron", last_name: "Riesler").first_or_create!(display_name: "Ron", level: open)
Player.where(first_name: "Ruben", last_name: "Bautista").first_or_create!(display_name: "Ruben", level: pro)
Player.where(first_name: "Rudy", last_name: "Dominguez").first_or_create!(display_name: "Rudy D", level: open)
Player.where(first_name: "Rudy", last_name: "Estoque").first_or_create!(display_name: "Rudy E", level: open)
Player.where(first_name: "Rudy", last_name: "Torres").first_or_create!(display_name: "Rudy T", level: open)
Player.where(first_name: "Ryan", last_name: "Laws").first_or_create!(display_name: "Rudy L", level: open)
Player.where(first_name: "Rylan", last_name: "Hartnett").first_or_create!(display_name: "Rylan", level: open)
Player.where(first_name: "Sajal", last_name: "Ghamire").first_or_create!(display_name: "Sajal", level: open)
Player.where(first_name: "Santos", last_name: "Sambjon").first_or_create!(display_name: "Santos", level: pro)
Player.where(first_name: "Scott", last_name: "Slayton").first_or_create!(display_name: "Scott", level: open)
Player.where(first_name: "Shan", last_name: "Damani").first_or_create!(display_name: "Shan", level: open)
Player.where(first_name: "Shawn", last_name: "Polk").first_or_create!(display_name: "Shawn", level: open)
Player.where(first_name: "Stacy", last_name: "Novak").first_or_create!(display_name: "Stacy", level: open)
Player.where(first_name: "Stanton", last_name: "Oda").first_or_create!(display_name: "Stanton", level: open)
Player.where(first_name: "Stephanie", last_name: "Hefner").first_or_create!(display_name: "Stephanie", level: open)
Player.where(first_name: "Stephano", last_name: "Lopez").first_or_create!(display_name: "Stephano", level: open)
Player.where(first_name: "Stephen", last_name: "Poma").first_or_create!(display_name: "Stephen", level: open)
Player.where(first_name: "Steve", last_name: "Chaplin").first_or_create!(display_name: "Steve C", level: open)
Player.where(first_name: "Steve", last_name: "Mansfield").first_or_create!(display_name: "Steve M", level: open)
Player.where(first_name: "Sy", last_name: "Nakashima").first_or_create!(display_name: "Sy", level: semi_pro)
Player.where(first_name: "Tang", last_name: "Hoa").first_or_create!(display_name: "Tang", level: semi_pro)
Player.where(first_name: "Teresa", last_name: "Mojica").first_or_create!(display_name: "Teresa", level: open)
Player.where(first_name: "Tim", last_name: "Daniel").first_or_create!(display_name: "Tim", level: open)
Player.where(first_name: "Tina", last_name: "Hess").first_or_create!(display_name: "Tina", level: open)
Player.where(first_name: "Tom", last_name: "Hardinger").first_or_create!(display_name: "Tom H", level: open)
Player.where(first_name: "Tom", last_name: "Smith").first_or_create!(display_name: "Tom S", level: open)
Player.where(first_name: "Tommy", last_name: "Lipps").first_or_create!(display_name: "Tommy", level: open)
Player.where(first_name: "Tony", last_name: "Rodiguez").first_or_create!(display_name: "Tony", level: open)
Player.where(first_name: "Tres", last_name: "Kane").first_or_create!(display_name: "Tres", level: open)
Player.where(first_name: "Trinh", last_name: "Lu").first_or_create!(display_name: "Trinh", level: open)
Player.where(first_name: "Tyler", last_name: "Van Wulven").first_or_create!(display_name: "Tyler", level: open)
Player.where(first_name: "Vicki", last_name: "Wade").first_or_create!(display_name: "Vicki", level: open)
Player.where(first_name: "Victor", last_name: "Ignacio").first_or_create!(display_name: "Victor I", level: semi_pro)
Player.where(first_name: "Victor", last_name: "Valseca").first_or_create!(display_name: "Victor V", level: open)
Player.where(first_name: "Vilmos", last_name: "Foldes").first_or_create!(display_name: "Vilmos", level: pro)
Player.where(first_name: "Wayne", last_name: "Larson").first_or_create!(display_name: "Wayne", level: open)
Player.where(first_name: "Wei", last_name: "Ni").first_or_create!(display_name: "Wei", level: open)
Player.where(first_name: "Yoli", last_name: "Hakanado").first_or_create!(display_name: "Yoli", level: open)
Player.where(first_name: "Yvonne", last_name: "Asher").first_or_create!(display_name: "Yvonne", level: open)
Player.where(first_name: "Zeke", last_name: "Morrison").first_or_create!(display_name: "Zeke", level: semi_pro)
